{
 "title": "Linky",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   { "name": "subscription_price", "query": "10.596666667" },
   { "name": "unit_price", "query": "0.1582" },
   { "name": "adco", "query": { "query": "linky_papp" } },
   { "name": "optarif", "query": { "query": "linky_papp" } }
  ]
 },
 "panels": [
  {
   "title": "Adresse compteur",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "${adco}" }
   ]
  },
  {
   "title": "Puissance souscrite",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kvoltamp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "(linky_isousc * 200)/1000" }
   ]
  },
  {
   "title": "Intensité souscrite",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "linky_isousc" }
   ]
  },
  {
   "title": "Puissance apparente",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kvoltamp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "linky_papp/1000" }
   ]
  },
  {
   "title": "Intensité instantanée",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "linky_iinst" }
   ]
  },
  {
   "title": "Index option Base",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "linky_base" }
   ]
  },
  {
   "title": "Consolation période",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "delta(linky_base[$__range])" }
   ]
  },
  {
   "title": "Coût période",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(delta(linky_base[$__range])/1000)*${unit_price}"
    }
   ]
  },
  {
   "title": "Abonnement mensuel",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "${subscription_price}" }
   ]
  },
  {
   "title": "Puissance apparente",
   "type": "graph",
   "gridPos": { "h": 10, "w": 7, "x": 3, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "kvoltamp" } },
   "yaxes": [
    { "format": "kvoltamp" }
   ],
   "targets": [
    { "expr": "linky_papp / 1000\n", "legendFormat": "Puissance apparente" },
    { "expr": "(linky_isousc * 200)/1000", "legendFormat": "Puissance souscrite" }
   ]
  },
  {
   "title": "Intensité instantanée",
   "type": "graph",
   "gridPos": { "h": 10, "w": 7, "x": 10, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "yaxes": [
    { "format": "amp" }
   ],
   "targets": [
    { "expr": "linky_iinst", "legendFormat": "Intensité instantanée" },
    { "expr": "linky_isousc", "legendFormat": "Intensité souscrite" }
   ]
  },
  {
   "title": "Index option Base",
   "type": "graph",
   "gridPos": { "h": 10, "w": 7, "x": 17, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "yaxes": [
    { "format": "watth" }
   ],
   "targets": [
    { "expr": "linky_base", "legendFormat": "Index" }
   ]
  },
  {
   "title": "Prix du KWh",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "${unit_price}" }
   ]
  }
 ]
}